### PR TITLE
Make code more resilient to a non-existing step

### PR DESCRIPTION
**Pull request by rixx**

### CODE REVIEW

**Comment by rixx** [comment]
Is there anything I should add or change? I'm happy to work with you to get this merged.

**Comment by rixx** [comment]
Ping? This is a real-life issue for me, and I'd like to stop running a patched library. Anything I can do to get this merged?

**Comment by claudep** [comment]
Yes, you can, by adding tests!

**Comment by rixx** [comment]
Done – the submitted test throws a `ValueError` in the current master, and returns an expected result in my patch.

**Comment by claudep** [comment]
Awesome, thanks! The test failures are unrelated to the patch.

**Pull request merged**
