### PR TITLE
Added request parameter to FormPreview.parse_params - fixes #22

### LINKED ISSUE #22: FormPreview should pass request object to parse_params
This issue was originally submitted on [Trac (#8690)](https://code.djangoproject.com/ticket/8690). See the previous link for the full conversation. Below is the original description:

---

It would be very useful to have request data in `parse_params`. The example given is to capture something like a `user_id`, but the main thing I would want to do here is to verify that the current user has permission to access the URL given. Of course, adding a parameter breaks backwards compatibility, so this is a similar request to http://code.djangoproject.com/ticket/7222.

### PR DESCRIPTION
**Pull request by gchp**

### CODE REVIEW

**Comment by gchp** [comment]
I'm not quite sure why travis is failing. The `py27-django-master` test run is what's causing it, but this is passing for me locally. Perhaps just an issue with travis?

**Comment by jezdez** [comment]
@gchp I've updated the Travis config to use GitHub's tarballs for the master test environment because the zip file handling in pip is somehow broken. If you rebase on top of master it should pass the tests.

**Comment by gchp** [comment]
@jezdez cool! I've just updated now, let's see how it goes :)

**Comment by jezdez** [comment]
@gchp I'm about to do the 1.0 release, let's move this to the next one

**Comment by gchp** [comment]
@jezdez sure, no prob.

**Comment by gchp** [comment]
Your fix worked, anyway!

**Pull request merged**
