### PR TITLE
Added 2.0 section to changelog & moved item from 1.0 list

### PR DESCRIPTION
**Pull request by gchp**

### CODE REVIEW

**Comment by timgraham** [comment]
Hi Greg, was there any discussion about how version numbering will work? I was going to do a release for Django 1.10 compatibility, but wasn't sure if 2.0 is the appropriate version number at this ponit. I thought it might be interesting to match versions with Django (e.g. django-formtools 1.10 would be 1.10 compatible) but I don't have a strong opinion about that.

**Comment by jezdez** [comment]
@timgraham Chiming in, I'd caution to use the same version numbers as Django as it implies that the package won't be able to have own minor and bugfix releases, or at least it quickly can become messy and less intuitive to parse the version. Instead it should follow the same pattern as Django uses for Python compatibility -- support a certain range of Django versions (the supported one basically), and document which versions of django-formtools work with which.

**Comment by jezdez** [comment]
As to whether 2.0 is the next logical step, I'd look at the features/bug fixes since the last release and if there is a backward-incompatible change, just use 2.0.

**Comment by timgraham** [comment]
Support for Django 1.7 is dropped, so I guess 2.0 it is.

**Pull request merged**
